export const dropdownValues = [
  "Summarize key findings or arguments",
  "Compare and contrast different approaches or perspectives",
  "Identify trends or patterns in the research literature",
  "Evaluate the quality or credibility of the research",
  "Explore potential areas for future research",
  "Analyze methodology used",
  "Identify key theoretical frameworks or concepts",
  "Evaluate evidence presented in support of claims",
  "Examine ethical implications",
  "Identify potential applications or practical implications",
  "Assess impact on the field",
];

export const filterOptions = [
  {
    id: "1",
    name: "Name",
    field: "file_name",
    visible: true,
    width: "450px",
    font_size: "12px",
    truncate: false,
  },
  {
    id: "2",
    name: "Privacy",
    field: "privacy",
    visible: false,
    width: "250",
    font_size: "12px",
    truncate: false,
  },
  {
    id: "3",
    name: "Review Stage",
    field: "status",
    visible: true,
    width: "150px",
    font_size: "12px",
    truncate: false,
  },
  {
    id: "4",
    name: "Tags",
    field: "tags",
    visible: true,
    width: "150px",
    font_size: "12px",
    truncate: false,
  },
  {
    id: "5",
    name: "Pages",
    field: "number_of_page",
    visible: false,
    width: "150px",
    font_size: "12px",
    truncate: false,
  },
  {
    id: "6",
    name: "Size",
    field: "size",
    visible: false,
    width: "150px",
    font_size: "12px",
    truncate: false,
  },
  {
    id: "7",
    name: "Date Processed",
    field: "last_update",
    visible: false,
    width: "150px",
    font_size: "12px",
    truncate: false,
  },
  {
    id: "8",
    name: "User",
    field: "upload_user_email",
    visible: false,
    width: "150px",
    font_size: "12px",
    truncate: false,
  },
  {
    id: "9",
    name: "Status",
    field: "ai_status",
    visible: true,
    width: "150px",
    font_size: "12px",
    truncate: false,
  },
  {
    id: "10",
    name: "Citations",
    field: "citations",
    visible: false,
    width: "150px",
    font_size: "12px",
    truncate: false,
  },
  {
    id: "11",
    name: "Authors",
    field: "authors",
    visible: false,
    width: "150px",
    font_size: "12px",
    truncate: false,
  },
  {
    id: "12",
    name: "Publication Year",
    field: "publication_year",
    visible: false,
    width: "150px",
    font_size: "12px",
    truncate: false,
  },
  {
    id: "13px",
    name: "Publication Date",
    field: "publication_date",
    visible: false,
    width: "150px",
    font_size: "12px",
    truncate: false,
  },
  {
    id: "14",
    name: "Publication Detail",
    field: "publication_detail",
    visible: false,
    width: "450",
    font_size: "12px",
    truncate: false,
  },
  {
    id: "15",
    name: "Summary",
    field: "summary",
    visible: false,
    width: "450",
    font_size: "12px",
    truncate: false,
  },
  {
    id: "16",
    name: "Keyword",
    field: "keyword",
    visible: false,
    width: "150px",
    font_size: "12px",
    truncate: false,
  },
  {
    id: "17",
    name: "Research Methods",
    field: "research_methods",
    visible: false,
    width: "450",
    font_size: "12px",
    truncate: false,
  },
  {
    id: "18",
    name: "Weakness & Strength",
    field: "weakness_strength",
    visible: false,
    width: "450",
    font_size: "12px",
    truncate: false,
  },
  {
    id: "19",
    name: "Future Directions",
    field: "future_directions",
    visible: false,
    width: "450",
    font_size: "12px",
    truncate: false,
  },
  {
    id: "20",
    name: "Limitations",
    field: "limitations",
    visible: false,
    width: "450",
    font_size: "12px",
    truncate: false,
  },
  {
    id: "21",
    name: "Research Approach",
    field: "research_approach",
    visible: false,
    width: "450",
    font_size: "12px",
    truncate: false,
  },
  {
    id: "22",
    name: "Author Affiliation",
    field: "author_affiliation",
    visible: false,
    width: "450",
    font_size: "12px",
    truncate: false,
  },
];
