export const subsciptionPlans: any = [
  {
    title: "Free (14 day trial)",
    price: 0,
    subscriptionPlan: "free",
    features: [
      "15GB storage",
      "Search across 250+ million papers",
      "Export options (RIS, CSV, BIB, PubMed, Zotero)",
      "Search across 250+ million papers",
      "Access to core features like basic search and summarization",
      "AI Model Access (Latest AI Models: GPT, Claude, Llama, Perplexity)",
      "50 Notes and 50 Bookmarks",
      "AI Chat with Paper",
      "Summarize Paper",
      "Team Collaboration",
      "Topic Explorer",
      "Reference Management",
      "Sync with Zotero",
      "6000/month AI Credits",
      "2 Workspaces",
      "6 Projects",
      "5 Custom Templates",
    ],
  },
  {
    title: "Plus",
    price: 14.99,
    billing: "billed annually",
    subscriptionPlan: "plus-plan-stripe",
    discountSubscriptionPlan: "plus-plan-discount",
    features: [
      "15GB storage",
      "Search across 250+ million papers",
      "Export options (RIS, CSV, BIB, PubMed, Zotero)",
      "Search across 250+ million papers",
      "Access to core features like basic search and summarization",
      "AI Model Access (Latest AI Models: GPT, Claude, Llama, Perplexity)",
      "50 Notes and 50 Bookmarks",
      "AI Chat with Paper",
      "Summarize Paper",
      "Team Collaboration",
      "Topic Explorer",
      "Reference Management",
      "Sync with Zotero",
      "6000/month AI Credits",
      "2 Workspaces",
      "6 Projects",
      "5 Custom Templates",
    ],
  },
  {
    title: "Pro",
    price: 34.99,
    subscriptionPlan: "pro-plan-stripe",
    discountSubscriptionPlan: "pro-plan-discount",
    billing: "billed annually",
    features: [
      "70GB storage",
      "Search across 250+ million papers",
      "Export options (RIS, CSV, BIB, PubMed, Zotero)",
      "Search across 250+ million papers",
      "Access to core features like basic search and summarization",
      "AI Model Access (Latest AI Models: GPT, Claude, Llama, Perplexity)",
      "Unlimited Notes and Unlimited Bookmarks",
      "AI Chat with Paper",
      "Summarize Paper",
      "Team Collaboration",
      "Topic Explorer",
      "Reference Management",
      "Sync with Zotero",
      "25000/month AI Credits",
      "5 Workspaces",
      "12 Projects",
      "15 Custom Templates",
      "Priority Support",
    ],
  },
];
